#Use this file to ensure that required variables are defined.


# Checking that required variables are set
#
#- name: Checking that required variables are set
#  fail: msg="{{ item }} is not defined"
#  when: item not in vars
#  loop:
#    - foobar_database
#    - foobar_deploy_user