# Installing kubernetes primitives
# Assuming 'apt'/'ubuntu'
---
- name: install APT Transport HTTPS
  apt:
    name: 
    - apt-transport-https
    - ca-certificates
    - curl
    state: present
- name: add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
- name: add Kubernetes' APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes.list'
- name: install kubelet
  apt:
    name: kubelet
    state: present
    update_cache: true
- name: install kubeadm
  apt:
    name: kubeadm
    state: present
- name: adding kubcectl shortcuts and completion
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: "source <(kubectl completion bash)\nalias k=kubectl\ncomplete -F __start_kubectl k\nalias xCNI='iptables -t nat -I KUBE-SERVICES -d 10.96.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-MARK-MASQ'"
